apiVersion: v1
kind: Pod
metadata:
  labels:
    name: loop
  name: loop
spec:
  containers:
    - image: "docker.io/centos:centos7"
      imagePullPolicy: IfNotPresent
      name: loop
      command: ["/bin/sh", "-c", "while :; do sleep 2; date; done"]
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  dnsPolicy: ClusterFirst
  serviceAccount: ""
  volumes:
    - emptyDir: {}
      name: tmp
