apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
    - image: "docker.io/xxxx/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: hello-pod
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts:
        - mountPath: /tmp
          name: workdir
  restartPolicy: OnFailure
  dnsPolicy: ClusterFirst
  serviceAccount: ""
  volumes:
    - emptyDir: {}
      name: workdir
