apiVersion: v1
kind: Pod
metadata: 
  creationTimestamp: ~
  labels: 
    name: hello-openshift
  name: hello-openshift
spec: 
  containers: 
    - 
      capabilities: {}
      image: "deshuai/hello-openshift:root"
      imagePullPolicy: IfNotPresent
      name: hello-openshift
      ports: 
        - 
          containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext: 
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts: 
        - 
          mountPath: /tmp
          name: tmp
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
    - 
      emptyDir: {}
      name: tmp
