apiVersion: v1
kind: List
items:
  #Succeeded pod
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-pod-1
    name: hello-pod-1
  spec:
    containers:
      - image: "docker.io/ocpqe/hello-pod:latest"
        command: ["sh", "-c", "exit 0"]
        imagePullPolicy: IfNotPresent
        name: hello-pod-1
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /tmp
            name: tmp
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: ""
    volumes:
      - emptyDir:
         medium: Memory
        name: tmp
  #Failed pod
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-pod-2
    name: hello-pod-2
  spec:
    containers:
      - image: "docker.io/ocpqe/hello-pod:latest"
        command: ["sh", "-c", "exit 1"]
        imagePullPolicy: IfNotPresent
        name: hello-pod-2
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /tmp
            name: tmp
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: ""
    volumes:
      - emptyDir:
         medium: Memory
        name: tmp
