apiVersion: v1
kind: List
items:
  #Succeeded pod
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-pod
    name: hello-pod
  spec:
    containers:
      - image: "docker.io/ocpqe/hello-pod:latest"
        command: ["sh", "-c", "dd if=/dev/zero of=/tmp/test1 bs=1M count=1024; exit 0"]
        imagePullPolicy: IfNotPresent
        name: hello-pod
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /tmp
            name: tmp
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: ""
    volumes:
      - hostPath:
          path: /tmp
        name: tmp
  #Failed pod
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-pod-1
    name: hello-pod-1
  spec:
    containers:
      - image: "docker.io/ocpqe/hello-pod:latest"
        command: ["sh", "-c", "dd if=/dev/zero of=/mnt/test2 bs=1M count=1024; exit 1"]
        imagePullPolicy: IfNotPresent
        name: hello-pod-1
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /mnt
            name: mnt
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: ""
    volumes:
      - hostPath:
          path: /mnt
        name: mnt
