apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: hello-pod
  name: hello-pod
spec:
  replicas: 1
  selector:
    run: hello-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-pod
    spec:
        containers:
        - image: docker.io/deshuai/hello-pod:latest
          imagePullPolicy: Always
          name: hello-pod
          ports:
          - containerPort: 8080
            protocol: tcp
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        activeDeadlineSeconds: 60
