apiVersion: v1
kind: Pod
metadata:
  labels:
    name: toleration-1
  name: toleration-1
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: toleration-1
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: ""
  tolerations: 
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoExecute"
