--- 
apiVersion: v1
kind: Pod
metadata: 
  annotations: 
    build: one
    builder: qe-one
  labels: 
    rack: a111
    region: r1
    zone: z11
  name: pod-dapi-volume
spec: 
  containers: 
    - 
      command: 
        - sh
        - "-c"
        - "while true; do if [[ -e /var/tmp/podinfo/labels ]]; then cat /var/tmp/podinfo/labels; fi; if [[ -e /var/tmp/podinfo/annotations ]]; then cat /var/tmp/podinfo/annotations; fi; sleep 5; done"
      image: gcr.io/google_containers/busybox
      name: client-container
      securityContext: 
        privileged: false
      volumeMounts: 
        - 
          mountPath: /var/tmp/podinfo
          name: podinfo
          readOnly: false
  securityContext: 
    fsGroup: 1234
  volumes: 
    - 
      downwardAPI: 
        items: 
          - 
            fieldRef: 
              fieldPath: metadata.labels
            path: labels
          - 
            fieldRef: 
              fieldPath: metadata.annotations
            path: annotations
          - 
            fieldRef: 
              fieldPath: metadata.name
            path: name
          - 
            fieldRef: 
              fieldPath: metadata.namespace
            path: namespace
      name: podinfo
