apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  finalizers:
  - kubernetes-incubator/service-catalog
  name: ansible-service-broker
spec:
  url: http://asb.openshift-ansible-service-broker.svc:1338
