apiVersion: v1
kind: Pod
metadata:
  labels:
    name: multi-containers
  name: multi-containers
spec:
  containers:
    - image: "docker.io/centos:centos7"
      name: test1
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo hello test1"]
    - image: "docker.io/centos:centos7"
      name: test2
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo hello test2"]
    - image: "docker.io/centos:centos7"
      name: test3
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo hello test3"]
    - image: "docker.io/centos:centos7"
      name: test4
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo hello test4"]
    - image: "docker.io/centos:centos7"
      name: test5
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo hello test5"]
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
  serviceAccount: ""
  volumes:
    - emptyDir: {}
      name: tmp
status: {}
